In [2]:
import pandas as pd
import numpy as np

In [3]:
ds=pd.read_csv("nba.csv")

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [5]:
ds.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [8]:
ds.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          0
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [7]:
ds["Age"].fillna(ds['Age'].mean(),inplace=True)

In [9]:
ds['Position'] = ds['Position'].astype('string')

In [10]:
ds['Age']=ds['Age'].astype('int')

In [14]:
ds['College'].fillna('Unknown',inplace=True)

In [16]:
ds["Salary"].fillna(ds['Salary'].mean(),inplace=True)

In [17]:
ds.isnull().sum()

Name        1
Team        1
Number      1
Position    1
Age         0
Height      1
Weight      1
College     0
Salary      0
dtype: int64

In [18]:
ds.dropna(subset=['Name','Team','Number','Position','Height','Weight'],inplace=True)

In [19]:
ds.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [20]:
ds['Name'] = ds['Name'].astype('string')

In [21]:
ds['Team'] = ds['Team'].astype('string')

In [22]:
ds['Position'] = ds['Position'].astype('string')

In [23]:
ds['College'] = ds['College'].astype('string')

In [25]:
ds.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,SF,25,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,SG,27,6-5,205.0,Boston University,4.842684e+06
3,R.J. Hunter,Boston Celtics,28.0,SG,22,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,PF,29,6-10,231.0,Unknown,5.000000e+06

In [29]:
ds.dtypes

Name        string[python]
Team        string[python]
Number             float64
Position    string[python]
Age                  int64
Height              object
Weight             float64
College     string[python]
Salary             float64
dtype: object

In [30]:
numeric_cols = ['Age', 'Height', 'Weight', 'Salary']
for col in numeric_cols:
    ds[col] = pd.to_numeric(ds[col], errors='coerce')

In [35]:
categorical_var = "Position"
numeric_vars = ["Age", "Weight", "Salary"]

In [36]:
grouped_stats = ds.groupby(categorical_var)[numeric_vars].agg(['mean', 'median', 'min', 'max', 'std'])
print(grouped_stats) #Group by categorical variable and get summary statistics

                Age                               Weight                       \
               mean median min max       std        mean median    min    max
Position
C         27.371795   27.0  20  40  4.156388  254.205128  250.0  220.0  307.0
PF        27.160000   27.0  20  40  4.607241  240.430000  240.0  200.0  275.0
PG        26.847826   26.5  20  40  4.169314  189.478261  190.0  161.0  220.0
SF        26.858824   26.0  20  38  4.386540  221.776471  225.0  175.0  260.0
SG        26.539216   25.0  19  39  4.643043  206.686275  209.5  175.0  234.0

                           Salary                                   \
                std          mean     median       min         max
Position
C         15.974297  5.967052e+06  3811060.0   83397.0  22359364.0
PF        12.591688  4.570889e+06  3000000.0  111444.0  22192730.0
PG        11.422436  5.067606e+06  3106518.0   55722.0  21468695.0
SF        14.286504  4.857220e+06  2041080.0   30888.0  25000000.0
SG        12.857929  4.034356e+06  2394102.5   55722.0  20000000.0


                   std
Position
C         5.787989e+06
PF        4.727010e+06
PG        4.939768e+06
SF        5.975997e+06
SG        4.426658e+06

In [40]:
position_salary_list = ds.groupby("Position")["Salary"].mean()
print(position_salary_list)

Position
C     5.967052e+06
PF    4.570889e+06
PG    5.067606e+06
SF    4.857220e+06
SG    4.034356e+06
Name: Salary, dtype: float64